[project]
name = "ocr_lista-escolar"
version = "0.0.1"
description = "Estração de dados estruturados em forma de texto a partir de imagem"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.35.63",
    "boto3-stubs[textract]>=1.35.63",
]
