[project]
name = "reconhecimento-celebridades"
version = "0.0.1"
description = "Reconhecimento facial de personalidades do mundo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.35.64",
    "boto3-stubs[rekognition]>=1.35.64",
    "pillow>=11.0.0",
]
